
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Sep 21 16:10:03 COT 2021
//----------------------------------------------------

package logica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Extern = 50;
  public static final int Op_atribucion = 21;
  public static final int Return = 53;
  public static final int Op_booleano = 23;
  public static final int Llave_c = 30;
  public static final int Llave_a = 29;
  public static final int Std = 66;
  public static final int Linea = 2;
  public static final int Break = 39;
  public static final int Coma = 28;
  public static final int Parent_c = 27;
  public static final int Parent_a = 26;
  public static final int Corchete_c = 32;
  public static final int Corchete_a = 31;
  public static final int Long = 44;
  public static final int Punto = 35;
  public static final int Default = 48;
  public static final int Char = 43;
  public static final int For = 10;
  public static final int Else = 7;
  public static final int Try = 68;
  public static final int Resta = 15;
  public static final int Int = 11;
  public static final int Cin = 61;
  public static final int Suma = 14;
  public static final int Using = 64;
  public static final int ERROR = 72;
  public static final int Cadena = 5;
  public static final int Typedef = 58;
  public static final int T_dato = 4;
  public static final int Op_Mayor = 24;
  public static final int Main = 33;
  public static final int Do = 8;
  public static final int Op_relacional = 20;
  public static final int P_coma = 34;
  public static final int Unsigned = 56;
  public static final int Short = 55;
  public static final int Scanf = 60;
  public static final int Case = 40;
  public static final int Sencilla = 70;
  public static final int Const = 46;
  public static final int Endl = 71;
  public static final int Continue = 47;
  public static final int Byte = 41;
  public static final int If = 6;
  public static final int Define = 67;
  public static final int EOF = 0;
  public static final int Catch = 69;
  public static final int Cout = 59;
  public static final int Numero = 37;
  public static final int Struct = 57;
  public static final int Division = 17;
  public static final int Namespace = 65;
  public static final int error = 1;
  public static final int Comillas = 3;
  public static final int Enum = 49;
  public static final int Potencia = 18;
  public static final int Op_Menor = 25;
  public static final int Float = 45;
  public static final int Identificador = 36;
  public static final int Op_incremento = 22;
  public static final int D_puntos = 42;
  public static final int Include = 63;
  public static final int Printf = 62;
  public static final int Register = 52;
  public static final int Igual = 13;
  public static final int Doble = 12;
  public static final int Goto = 51;
  public static final int While = 9;
  public static final int Union = 54;
  public static final int Op_logico = 19;
  public static final int Multiplicacion = 16;
  public static final int Switch = 38;
}

